const fonts = require('./fonts.cjs');
module.exports = (winvars) => {
  let m = '';
  for (let k = 1; k <= 6; k++) { m += `#ladder.m${k} .cur{opacity:0}#ladder.m${k} .s${k} .cur{opacity:1;animation:llCur 1s ease-in-out infinite}`; for (let j = 1; j <= k; j++) m += `#ladder.m${k} .s${j} .dim{opacity:0}`; }
  return `/* Lucky Llama Fiesta slot.css (leo): GENERATED by art/build.cjs. Add your own CSS after the KAI marker at the bottom. */
${fonts()}
:root{--ink:#2a1209;--gold:#f6b72a;--accent:#1cb8bd;--panel1:#a8572a;--panel2:#5a2810;--rim:#ffd27a;--rivet:#fff0b8;--bevel:#b8761a;--btn:#d92b78;--txt:#fff3d8;--muted:#f0d4b0;--acc1:#ffd23f;--acc2:#1cb8bd;--paper:#fff3d8;--hover:#c4723a;--toon:'LlLuck','Luckiest Guy',Impact,sans-serif}

/* ---------- layout: 1600x900 stage, NO side character. BOARD = 5x3 cells of 150 px = 750x450 at (425,190): right edge 1175, bottom 640 ---------- */
#scene{pointer-events:none}
#scene img{position:absolute;display:block;pointer-events:none}
#scene img.bdp{left:0;top:0;width:100%;height:100%;opacity:0}
#scene .bg{left:0;top:0;width:1600px;height:900px}
#scene .dusk{opacity:0;transition:opacity 1.6s}
#scene.bonus .dusk{opacity:1}
#scene .banners{left:0;top:0;width:1600px;height:420px;transform-origin:50% 0;animation:llSway 6s ease-in-out infinite alternate}
@keyframes llSway{0%{transform:skewX(-.7deg) translateX(-3px)}100%{transform:skewX(.7deg) translateX(3px)}}
#logo.off{opacity:0}
#logo{transition:opacity .4s;position:absolute;left:584px;top:2px;width:432px;height:142px;overflow:visible;pointer-events:none;z-index:3}
#frameArt{position:absolute;left:365px;top:152px;width:870px;height:528px;display:block;pointer-events:none}
#frame{left:425px;top:190px;width:750px;height:450px}
#grid{position:relative;display:grid;grid-template-columns:repeat(5,150px);grid-template-rows:repeat(3,150px);width:750px;height:450px;overflow:hidden;background:rgba(0,0,0,0)}
#fxl{position:absolute;inset:0;z-index:6;pointer-events:none}
.cell{margin:2px;min-width:0;min-height:0;position:relative;background:none;border:0}
.cell svg.g{position:absolute;left:0;top:0;width:100%;height:100%;overflow:visible;z-index:1}
.cell.hit{z-index:2}
#grid.focus .cell:not(.hit):not(.win){opacity:.55;filter:saturate(.7);transition:.25s}
.cell.sticky::after{content:"";position:absolute;inset:-2px;z-index:3;pointer-events:none;background:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 128 128'%3E%3Crect x='3' y='3' width='122' height='122' rx='16' fill='none' stroke='%23ff5ac0' stroke-opacity='.6' stroke-width='9'/%3E%3Crect x='4' y='4' width='120' height='120' rx='15' fill='none' stroke='%23ffd23f' stroke-width='4'/%3E%3C/svg%3E") center/100% 100% no-repeat;animation:llSt 1.4s ease-in-out infinite}
@keyframes llSt{0%,100%{opacity:.75}50%{opacity:1}}
@keyframes llCur{0%,100%{opacity:.55}50%{opacity:1}}
.sirSplash,.llSplash{width:400px;height:347px;display:block;margin:0 auto;overflow:visible}

/* ---------- side pieces ---------- */
#side{position:absolute;left:0;top:0;width:1600px;height:900px;pointer-events:none}
#ladderW{position:absolute;left:262px;top:150px;width:88px;height:490px}
#ladder{display:block;overflow:visible}
#ladder .dim{transition:opacity .35s}
#ladder.pop{animation:llPop .5s ease-out}
@keyframes llPop{0%{transform:scale(1)}40%{transform:scale(1.07)}100%{transform:scale(1)}}
${m}
#side .plate,#side .jp{position:absolute;display:none}
#side .plate.on,#side .jp.on{display:block}
#side .plate svg,#side .jp svg{display:block}
#side b,#side span{font-family:var(--toon);font-style:normal;font-weight:400;color:#ffd23f;text-shadow:2px 2px 0 var(--ink),-2px 2px 0 var(--ink),2px -2px 0 var(--ink),-2px -2px 0 var(--ink);position:absolute;text-align:center;white-space:nowrap}
#jps{position:absolute;left:1262px;top:190px;width:220px;height:372px}
#jps .jp{position:relative;margin-bottom:12px;display:none;--lit:0}
#jps .jp.on{display:block}
#jps .jp.lit{--lit:1}
#jps .jp.hit{animation:llPop .6s ease-out}
.jv{left:124px;top:20px;width:80px;height:44px;line-height:44px;font-size:24px}
#lkRespins{left:640px;top:96px;width:320px;height:92px}
#lkRespinsN{left:228px;top:6px;width:68px;height:80px;line-height:80px;font-size:46px}
#lkTotal{left:540px;top:672px;width:520px;height:110px;transform-origin:50% 0;transform:scale(.8)}
#lkTotalV{left:210px;top:22px;width:288px;height:68px;line-height:68px;font-size:44px}
#coLine{left:540px;top:684px;width:520px;height:60px}
#coLineT{left:14px;top:9px;width:492px;height:42px;line-height:42px;font-size:24px;color:#5a2810;text-shadow:none}
#coWin{left:620px;top:600px;width:360px;height:96px}
#coWinV{left:120px;top:20px;width:218px;height:56px;line-height:56px;font-size:36px}
#pdSpins{left:36px;top:150px;width:300px;height:80px}
#pdSpinsN{left:18px;top:16px;width:90px;height:48px;line-height:48px;font-size:34px}
#pdCallSpins{left:635px;top:88px;width:330px;height:92px}
#pdCallSpinsN{left:18px;top:16px;width:130px;height:60px;line-height:60px;font-size:44px}
#pdCallMult{left:580px;top:88px;width:440px;height:92px}
#pdCallMultN{left:18px;top:16px;width:120px;height:60px;line-height:60px;font-size:44px}
#pdCollector{left:1290px;top:300px;width:300px;height:300px}
#pdCollector.swing svg{animation:llSwing .9s ease-in-out both;transform-origin:50% 90%}
@keyframes llSwing{0%{transform:rotate(0)}30%{transform:rotate(-10deg)}60%{transform:rotate(8deg) scale(1.05)}100%{transform:none}}
#grandPlate{left:450px;top:290px;width:700px;height:300px}
#grandV{left:200px;top:196px;width:300px;height:70px;line-height:70px;font-size:48px}
#side .plate.pop{animation:llPlatePop .25s ease-out}
@keyframes llPlatePop{0%{transform:scale(.6);opacity:0}100%{transform:none;opacity:1}}
.lockRing,.crackFx{position:absolute;pointer-events:none;overflow:visible}

${winvars}

/* KAI */
`;
};
