services:
  - type: web
    name: nebula-casino
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: START_BALANCE
        value: 0
      - key: TURSO_URL
        value: libsql://nebula-magenon123.aws-us-east-2.turso.io
      - key: TURSO_TOKEN
        sync: false
