const fs=require('fs'),path=require('path');
const dir=path.join(__dirname,'sym');
const files=fs.readdirSync(dir).filter(f=>/^s\d+\.cjs$/.test(f)).sort((a,b)=>parseInt(a.slice(1))-parseInt(b.slice(1)));
let out=' <!-- Koji\'s Cloudtop Tea House symbols (leo). Indigo ink outline, flat fills, flat shade lower right, no textures. Each symbol animates itself in .a-* groups gated by --win/--delay/--spd. -->\n';
for(const f of files){ out+='   '+require(path.join(dir,f))()+'\n'; }
out+='   '+require('./splash.cjs')()+'\n';
const dst=process.argv[2]||'/home/user/nebula/slotforge/slots/cloudtop-tea-house/symbols.svg';
fs.writeFileSync(dst,out);
// animations only exist while a cell is winning (idle symbols carry NO running/paused animations: they each cost a compositor layer)
const reg=require('./lib.cjs').registry||{};const decl=Object.values(reg).flat().join(';');
fs.writeFileSync(path.join(__dirname,'winvars.css'),'/* generated by art/build.cjs: releases the symbols\' win animations (see lib.cjs) */\n.cell.hit,.ctDragon,.winAnim{'+decl+'}\n');console.log('wrote',dst,files.length,'symbols',out.length,'bytes');
// keep the generated block inside slot.css (between markers)
{const cssP=path.join(__dirname,'..','slot.css');let css=fs.readFileSync(cssP,'utf8');const blk=fs.readFileSync(path.join(__dirname,'winvars.css'),'utf8');
 const A='/* ART-GEN winvars begin */',B='/* ART-GEN winvars end */';const sec=A+'\n'+blk+'.ctDragon{--win:running}\n'+B;
 if(css.includes(A)) css=css.replace(new RegExp(A.replace(/[*/]/g,'\\$&')+'[\\s\\S]*?'+B.replace(/[*/]/g,'\\$&')),()=>sec); else css=css.trimEnd()+'\n'+sec+'\n';
 fs.writeFileSync(cssP,css);console.log('slot.css winvars updated');}
