// concatenates the CSS parts into ../slot.css (tokens, layout, plates, scene, logo, side, character, win vars, fonts)
const fs = require('fs'), path = require('path'); const A = n => path.join(__dirname, n);
const parts = ['tokens.css', 'layout.css', 'plates.css', 'scene.css', 'logo.css', 'side.css', 'char.css', 'sweep.css', 'extra.css'].filter(n => fs.existsSync(A(n)));
let css = `/* Arctic Aurora Lodge ART CSS (leo). Generated by art/css.cjs from art/*.css parts: edit the parts, not this file. kai appends slot-specific bits at the very end (after /* KAI */). */\n`;
parts.forEach(n => css += `\n/* ===== ${n} ===== */\n` + fs.readFileSync(A(n), 'utf8'));
css += '\n/* ART-GEN winvars begin */\n' + fs.readFileSync(A('winvars.css'), 'utf8') + '\n/* ART-GEN winvars end */\n';
if (fs.existsSync(A('fonts.css'))) css += '\n/* ART-GEN fonts begin */\n' + fs.readFileSync(A('fonts.css'), 'utf8') + '\n/* ART-GEN fonts end */\n';
css += '\n/* KAI */\n';
fs.writeFileSync(path.join(__dirname, '../slot.css'), css); console.log('slot.css', (css.length / 1024) | 0, 'KB');
