// concatenates the CSS parts into ../slot.css (tokens, layout, plates, scene, logo, side, character, win vars, fonts)
const fs = require('fs'), path = require('path'); const A = n => path.join(__dirname, n);
const parts = ['tokens.css', 'layout.css', 'plates.css', 'scene.css', 'logo.css', 'side.css', 'char.css', 'sweep.css', 'flare.css', 'extra.css'].filter(n => fs.existsSync(A(n)));
let css = `/* Arctic Aurora Lodge ART CSS (leo). Generated by art/css.cjs from art/*.css parts: edit the parts, not this file. kai appends slot-specific bits at the very end (after the KAI marker). */\n`;
parts.forEach(n => css += `\n/* ===== ${n} ===== */\n` + fs.readFileSync(A(n), 'utf8'));
if (fs.existsSync(A('bake/ribbon.webp'))) css += `\n#flare{--rib:url("data:image/webp;base64,${fs.readFileSync(A('bake/ribbon.webp')).toString('base64')}")}\n`;
css += '\n/* ART-GEN winvars begin */\n' + fs.readFileSync(A('winvars.css'), 'utf8') + '\n/* ART-GEN winvars end */\n';
if (fs.existsSync(A('fonts.css'))) css += '\n/* ART-GEN fonts begin */\n' + fs.readFileSync(A('fonts.css'), 'utf8') + '\n/* ART-GEN fonts end */\n';
const OUT = path.join(__dirname, '../slot.css'); let kai = fs.existsSync(A('kai-section.css')) ? fs.readFileSync(A('kai-section.css'), 'utf8') : '';
if (fs.existsSync(OUT)) { const old = fs.readFileSync(OUT, 'utf8'); const i = old.indexOf('/* KAI */'); if (i >= 0 && old.slice(i + 9).trim().length > 50) kai = old.slice(i + 9); }
css += '\n/* KAI */' + kai;
fs.writeFileSync(path.join(__dirname, '../slot.css'), css); console.log('slot.css', (css.length / 1024) | 0, 'KB');
