// node css.cjs -> ../slot.css : art CSS parts + winvars + fonts + "/* KAI */" marker. kai appends his bits AFTER the marker; NEVER re-run this once kai has edited slot.css (it would drop his section) unless you merge by hand.
const fs = require('fs'), path = require('path'); const A = n => path.join(__dirname, n);
const out = path.join(__dirname, '../slot.css');
let kai = ''; if (fs.existsSync(out)) { const old = fs.readFileSync(out, 'utf8'); const i = old.indexOf('/* KAI */'); if (i >= 0) kai = old.slice(i + 9); }
const parts = ['tokens.css', 'layout.css', 'plates.css', 'seal.css', 'scene.css', 'logo.css', 'side.css', 'char.css', 'astro.css', 'splash.css', 'extra.css'].filter(n => fs.existsSync(A(n)));
let css = `/* Siroccos Lamp Bazaar ART CSS (leo). Generated by art/css.cjs from art/*.css parts: edit the parts, not this file. kai appends slot-specific bits at the very end (after the KAI marker; css.cjs keeps whatever is already there). */\n`;
parts.forEach(n => css += `\n/* ===== ${n} ===== */\n` + fs.readFileSync(A(n), 'utf8'));
css += '\n/* ART-GEN winvars begin */\n' + fs.readFileSync(A('winvars.css'), 'utf8') + '\n/* ART-GEN winvars end */\n';
css += '\n/* ART-GEN fonts begin */\n' + fs.readFileSync(A('fonts.css'), 'utf8') + '\n/* ART-GEN fonts end */\n';
css += '\n/* KAI */' + kai;
fs.writeFileSync(out, css); console.log('slot.css', (css.length / 1024) | 0, 'KB', kai ? '(kai section kept: ' + kai.length + ' chars)' : '');
